// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqqbzpgqntubnhgrxpet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxcWJ6cGdxbnR1Ym5oZ3J4cGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwODk2NzEsImV4cCI6MjA4NTY2NTY3MX0.12Vs06xkEQcTUL1Wx5PmBXEirREH7stbLv50_dQAm8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});